### ISSUE TITLE
can't load vignettes in terminal

### ISSUE THREAD

**Issue by priyanka8590** [arendsee/synder#6] opened 2017-06-22 02:25 UTC
After installing Synder in commandline, I couldn't load vignettes using the command line given. Is there a particular way I can do it?

**Comment by arendsee** [comment] 2017-06-22 04:17
I'm closing this question as a duplicate of #3 . You can post future comments about loading vignettes there. And I will work on getting a good solution.

**Closed as completed** 2017-06-22 04:18 UTC
Labels: duplicate
